<%@ Language="C#" MasterPageFile="~/Content.master" AutoEventWireup="true" %>

<asp:Content ID="contentHead" ContentPlaceHolderID="head" runat="server" >
<title>Centerfold Strips | Legal Terms</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css">
	#frameHolder #flashNav
	{
	    background-image: url('images/headerPrivacyPolicy.jpg');
	    background-repeat: no-repeat;	
	}
</style>

</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="partyLocationsHolder" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="mainContentHolder" Runat="Server">
<p>1. Privacy Statement; Collection of Personally Identifiable Information   (&quot;PII&quot;). Centerfold Strips. (&quot;CFS&quot;) operates this website. All references   to &quot;we&quot;, &quot;us&quot;, &quot;our&quot;, this &quot;website&quot; or this &quot;site&quot; shall be construed to mean   CFS. We understand that visitors to this website are concerned about the privacy   of information. The following describes our privacy policy regarding information   that we collect through this website, including OUR COLLECTION OF PERSONALLY   IDENTIFIABLE INFORMATION THAT MAY PERSONALLY IDENTIFY YOU (which we refer to in   this Privacy Policy as &quot;PII&quot;).</p>
<p>2. Modification of Privacy Policy. We reserve the right to modify this   Privacy Policy at any time, and without prior notice, by posting an amended   Privacy Policy that is always accessible by clicking on the &quot;Privacy Policy&quot;   link on this site's home page. Your continued use of this site indicates your   acceptance of the amended Privacy Policy. You should check the Privacy Policy   through this link periodically for modifications by clicking on the link   provided near the top of the Privacy Policy for a listing of material   modifications and their effective dates. Regarding PII, if any modifications are   materially less restrictive on our use or disclosure of the PII previously   disclosed by you, we will obtain your consent before implementing such revisions   with respect to such information.</p>
<p>3. Collection of Anonymous, Passive Information. We reserve the right to   monitor your use of this site. As you navigate through this site, certain   anonymous information may be passively collected (that is, gathered without your   actively providing the information) using various technologies, such as cookies,   Internet tags or web beacons, and navigational data collection (log files,   server logs, clickstream). For example, as explained in more detail below, your   Internet browser automatically transmits to this site some of this anonymous   information, such as the URL of the website you just came from and the Internet   Protocol (IP) address and the browser version your computer is currently using.   This site may also collect anonymous information from your computer through   cookies and Internet tags or web beacons. You may set your browser to notify you   when a cookie is sent or to refuse cookies altogether, but certain features of   this site might not work without cookies. The following is a listing and a brief   explanation of passive information collection methodologies which we may use   from time to time to better understand how this site is being used.</p>
<p>        3.1  A &quot;cookie&quot; is a bit of information that this site sends to your   Web browser which helps us remember information about you and your preferences. </p>
<p>        3.2  &quot;Session&quot; cookies are temporary bits of information that are   used to improve navigation, block visitors from providing information where   inappropriate (the site &quot;remembers&quot; previous entries of age or country of origin   that were outside the specified parameters and blocks subsequent changes), and   collect aggregate statistical information on the site. They are erased once you   exit your Web browser or otherwise turn off your computer. </p>
<p>        3.3  &quot;Persistent&quot; cookies are more permanent bits of information that   are placed on the hard drive of your computer and stay there unless you delete   the cookie. Persistent cookies store information on your computer for a number   of purposes, such as retrieving certain information you have previously   provided, helping to determine what areas of the site you may find most   valuable, and customizing the site based on your preferences on an ongoing   basis. Persistent cookies placed by this site in your computer do not hold PII.</p>
<p>        3.4  You can set your browser to accept all cookies, to reject all   cookies, or to notify you whenever a cookie is offered so that you can decide   each time whether to accept it. To learn more about cookies and how to specify   your preferences, please search for &quot;cookie&quot; in the &quot;Help&quot; portion of your   browser. </p>
<p>        3.5  An Internet Protocol (IP) address is a number assigned to your   computer by your Internet service provider so you can access the Internet and is   generally considered to be non-personally identifiable information, because in   most cases an IP address is dynamic (changing each time you connect to the   Internet), rather than static (unique to a particular user's computer). The IP   address can be used to diagnose problems with a server, report aggregate   information, determine the fastest route for your computer to use in connecting   to a site, and administer and improve the site. </p>
<p>        3.6  &quot;Internet tags&quot; (also known as Web Beacons, single-pixel GIFs,   clear GIFs, invisible GIFs, and 1-by-1 GIFs) are smaller than cookies and tell   the Web site server information such as the IP address and browser type related   to the visitor's computer. Tags may be placed both on online advertisements that   bring people to the site and on different pages of the site. Such tags indicate   how many times a page is opened and which information is consulted. </p>
<p>        3.7  &quot;Navigational data&quot; (log files, server logs, and clickstream   data) are used for system management, to improve the content of the site, market   research purposes, and to communicate information to visitors.</p>
<p>4. Use and Sharing of Anonymous, Passive Information. This site may make full   use of passively collected anonymous information through the collection methods   described above for our own internal operational purposes, including without   limitation the right to use such information to provide better service to site   visitors, customize the site based on your preferences, compile and analyze   statistics and trends, and otherwise administer and improve this site for your   use. We reserve the right to share this information in the same manner as   provided below for PII.</p>
<p>5. Use of 3rd Party Cookies; Google Analytics. This site reserves the right   to use web analytics services provided by third parties, such as the Google   Analytics service by Google, Inc. These services use cookies (sometimes referred   to as 3rd party cookies) which are text files placed on your computer, to help   us analyze how users use this site. The information generated by the cookie   about your use of this site (including your IP address) will be transmitted to   and stored by the service provider. The will use this information for the   purpose of evaluating your use of this site, compiling reports on website   activity for website operators, and providing other services relating to website   activity and internet usage. These services may also transfer this information   to third parties where required to do so by law, or where such third parties   process the information on the service's behalf. These services will not   associate your IP address with any other data held by Google. You may refuse the   use of cookies by selecting the appropriate settings on your browser; however,   please note that if you do this you may not be able to use the full   functionality of this site. By using this site, you consent to the processing of   data about you by third party analytics services in the manner and for the   purposes set out above.</p>
<p>6. Collection of PII. We will ask you when we need to collect PII (defined   above). PII which we collect may vary depending on the benefits and/or services   you select, and may include one or more of the following categories of   information: name, physical address, an email address, phone number, and credit   card information including credit card number, expiration date, and billing   address.</p>
<p>7. Use And Sharing of PII: General Policy. Except as discussed below, our   general policy is that we will use your PII only for the performance of the   services or transaction for which it was given, and we will not share, sell, or   rent your PII to others. The only exceptions to this general policy: (i) are   described in the subsections below, and (ii) if explicitly approved by you   through our site. WE WILL NEVER UNDER ANY CIRCUMSTANCES COMBINE PASSIVELY   COLLECTED INFORMATION WITH YOUR PII.</p>
<p>        7.1   Affiliates. Unless prohibited by law, we may use and share   PII within any companies that may legally affiliated with us (such as, for   example, any parent, subsidiary, or brother or sister entity) for purposes of   providing service and account maintenance, to help us design and improve   products and services, and to offer products and services that may be of   interest to you. </p>
<p>        7.2  Third-Party Service Providers. We may hire other companies to   provide services on our behalf. These third-party service providers may include,   for example, companies that (i) host, manage, and service our website, web   servers, software and systems, (ii) provide business or data processing   services, (iii) provide marketing services, (iv) provide payment processing,   fulfillment, and/or shipping services, (i) refer you to this site in their   capacity as our marketing partner or affiliate, and (vi) provide other new   services. We may share or make PII accessible to such third parties; however,   all such third parties are required to maintain the confidentiality of PII and   are prohibited from using PII for any purpose other than for the services they   provide, which may include emails, but only to the extent email is integral to   their services.</p>
<p>        7.3  In the Event of Merger, Sale, or Bankruptcy. In the event that   we are acquired by or merged with a third party entity, we reserve the right, in   any of these circumstances, to transfer or assign the information we have   collected from our users as part of such merger, acquisition, sale, or other   change of control. In the unlikely event of our bankruptcy, insolvency,   reorganization, receivership, or assignment for the benefit of creditors, or the   application of laws or equitable principles affecting creditors' rights   generally, we may not be able to control how your PII is treated, transferred,   or used.</p>
<p>        7.4  Legal Process. We reserve the right to share PII with third   parties in response to a subpoena, to prevent fraud, to comply with an inquiry   by a government agency or other regulator, or as necessary for other legal   purposes. </p>
<p>8. Onward Transfer of PII Outside Your Country of Residence. Any PII which we   may collect on this site will be stored and processed in our servers located   only in the United States. By using this site, if you reside outside the United   States, you consent to the transfer of PII outside your country of residence to   the United States.</p>
<p>9. Security of PII. We have adopted reasonable and appropriate security   measures to protect your PII and other sensitive information. Unfortunately, no   data transmission over the Internet or method of data storage can be guaranteed   100% secure. Therefore, while we strive to protect your PII with reasonable and   appropriate security measures, we cannot ensure or warrant the absolute security   of any information you transmit to us or archive at this site.</p>
<p>10. Making Changes To PII. Registered users may make changes to their PII. To   update your PII, login and click on the &quot;Modify Profile&quot; link at the top of the   page. Key in your updated information and click on the Set Profile button to   save.</p>
<p>11. Email From This Site; Opt-Out Rights. If you supply us with your e-mail   address you may receive periodic messages from us with information specific to   the site and required for the normal functioning of the site as well as for new   products or services or upcoming events. If you prefer not to receive periodic   email messages, you may opt-out by following the instructions on the email.</p>
<p>12. Links To Other Sites Including Online Ads. This website may contain links   to other websites with whom we have a business relationship. These links may   include online advertisements that we deem to be appropriate. The privacy   practices of these websites are not covered by our privacy policy, and we are   not responsible for the privacy practices or the content of these sites.   Additionally, if you register with any of these sites for any purpose or   purchase from any of these sites, any information that you provide in the   process of registration or purchase, such as your credit card number and other   PII, will be transferred to these sites. These sites have separate data   collection, data privacy, and data security policies and practices, and we have   no responsibility or liability for these independent policies and practices;   however, we have entered into agreements with these websites which provide that   UNLESS YOU SPECIFICALLY AGREE OTHERWISE (ii) they will use your PII only for the   purpose of providing the products or services that you may request, and (ii)   they will share your PII only as required to fulfill your request for products   or services. You should be careful to review any privacy policies posted on any   of these sites before providing information to them.</p>
<p>13. Children's Online Policy. We are committed to preserving online privacy   for all of its website visitors, including children. This site is a general   audience site. Consistent with the Children's Online Privacy Protection Act   (COPPA), we will not knowingly collect any information from, or sell to,   children under the age of 13. If you are a parent or guardian who has discovered   that your child under the age of 13 has submitted his or her personally   identifiable information without your permission or consent, we will remove the   information from our active list, at your request. To request the removal of   your child's information, please send contact our site as provided below under   &quot;Contact Us&quot;, and be sure to include in your message the same login information   that your child submitted. </p>
<p>14. Email And Other Messages Through This Site; ECPA Notice. This site treats   email messages and other electronic messages that are sent through this site and   not viewable by others as confidential and private, except as required by law,   including without limitation, the Electronic Communications Privacy Act of 1986,   18 U.S.C. Sections 2701-2711 (the &quot;ECPA&quot;). The ECPA permits this site's limited   ability to intercept and/or disclose electronic messages, for example (i) as   necessary to operate our system or to protect our rights or property, (ii) upon   legal demand (court orders, warrants, subpoenas), or (iii) where we receive   information inadvertently which appears to pertain to the commission of a crime.   This site is not considered a &quot;secure communications medium&quot; under the ECPA.</p>
<p>15. USA Patriot Act Notice. The federal USA Patriot Act (&quot;USA Patriot Act&quot;)   provides generally for the operator of a communication host and law enforcement   to be able to monitor any content, upon request of the operator. We anticipate   fully complying with all our obligations, and availing ourselves of all our   rights, under the USA Patriot Act.</p>
<p>16. Contact Us. If you have any questions regarding this Privacy Policy,   please contact the operator of this website at:</p>
<p>Centerfold Strips<br />
     <a href="mailto:info@centerfoldstrips.com">info@centerfoldstrips.com</a><br />
     Telephone: 877-427-8747<br />
</asp:Content>

