<%@ Language="C#" MasterPageFile="~/Content.master" AutoEventWireup="true" %>

<asp:Content ID="contentHead" ContentPlaceHolderID="head" runat="server" >
<title>Centerfold Strips | Legal Terms</title>
<meta name="keywords" content="" />
<meta name="description" content="" />
<style type="text/css">
	#frameHolder #flashNav
	{
	    background-image: url('../images/headerTermsofUse.jpg');
	    background-repeat: no-repeat;	
	}
</style>
</asp:Content>

<asp:Content ID="Content1" ContentPlaceHolderID="partyLocationsHolder" Runat="Server">
</asp:Content>

<asp:Content ID="Content2" ContentPlaceHolderID="mainContentHolder" Runat="Server">
<p><strong>PLEASE READ THESE TERMS OF USE CAREFULLY. BY ACCESSING OR OTHERWISE USING   THIS SITE, YOU AGREE TO BE BOUND CONTRACTUALLY BY THESE TERMS OF USE.</strong></p>
<p>1. Parties. The parties to this Agreement are you, a visitor to this web site   (&quot;You&quot;), and the owner and operator of this web site: CENTERFOLD STRIPS., a   New York corporation (&quot;CFS&quot;). All references to &quot;us&quot;, &quot;we&quot;, &quot;this web site&quot; or   &quot;this site&quot; shall be construed to mean CFS. If the user is not an individual,   then &quot;You&quot; means Your company, its officers, members, agents, successors and   assigns.</p>
<p>2. License. CFS grants a non-exclusive, non-transferable, and revocable   license to You and provides the services available at this site to You subject   to the following terms and conditions.</p>
<p>3. Entire Agreement. This Terms of Use Agreement will be expressly   incorporated by reference in each and every agreement between You and CFS, and   except for any separate license agreement for software and/or content, this   terms of use agreement supersedes any and all prior and existing agreements,   whether oral or in writing, between You and CFS with respect to the subjects   addressed herein and constitutes the entire agreement between the parties with   respect to those subjects. Except for any separate license agreement for   software and/or content, You acknowledge that neither CFS nor anyone on CFS's   behalf has made any representations, inducements, promises or agreements, orally   or otherwise, to You relating to the subjects addressed by this terms of use   agreement that are not embodied herein.</p>
<p>4. Prohibited Conduct. You agree (i) not to use this site to upload or   distribute in any way files that contain viruses, corrupted files, or any other   similar software or programs that may damage the operation of another's   computer; (ii) not to interfere or disrupt this site or any networks connected   to this site; (iii) not to use any device, software or routine or attempt to   interfere with the proper functioning of this site or any transactions being   offered at this site; (iv) not to take any action that imposes an unreasonable   or disproportionately large load on CFS's infrastructure; (v) not to use this   site to collect or harvest personal information, including, without limitation,   financial information, about other participants at this site; and (vi) not to   impersonate any person or entity or falsely state or otherwise misrepresent Your   affiliation with a person or entity. You agree not to use the services,   products, or downloads available at this site for illegal purposes, and to   comply with all regulations, policies and procedures of networks connected to   this site.</p>
<p>5. Compliance with Laws. You shall comply with all applicable laws and   regulations of the United States and foreign authorities (including, but not   limited to United States trade restriction laws, export laws or license   requirements and laws regarding the sale or transport of hazardous materials,   and laws regarding the transmission of technical data, including without   limitation encryption, exported from the United States through the services   available at this site) relating to any service, product, or download associated   with this site.</p>
<p>6. Separate License Agreement(s). You may acquire software and/or content   from CFS by download from this site, or otherwise directly from CFS. You agree   that your use of such software and/or content shall be strictly in accordance   with the applicable license agreement(s).</p>
<p>7. Registration Data And Privacy. Registration may be required for you to   download from this site, or for your participation in certain services offered   at this site. You must provide certain current, complete, and accurate   information about You as prompted to do so by the registration form   (&quot;Registration Data&quot;), and maintain and update such registration information as   required to keep such information current, complete and accurate. You warrant   that your Registration Data is accurate and current, and that You are authorized   to provide such Registration Data. You authorize us to verify your Registration   Data at any time. If any Registration Data that You provide is untrue,   inaccurate, not current or incomplete, CFS retains the right, in its sole   discretion, to suspend or terminate rights to use the services. Registration   Data and certain other information about You is subject to our Privacy Policy   which may be accessed from the Digicontracts.com home page. Solely to enable CFS   to use information You supply us internally, so that we are not violating any   rights You might have in that information, You grant to CFS a nonexclusive   license to (i) convert such information into digital format such that it can be   read, utilized and displayed by CFS's computers or any other technology   currently in existence or hereafter developed capable of utilizing digital   information, and (ii) combine the information with other content provided by   CFS, in each case by any method or means or in any medium whether now known or   hereafter devised.</p>
<p>8. Postings To This Site.</p>
<p>        8.1 Postings To Blog. We will not treat information that you post to   the blog on this site as proprietary, private, or confidential. We have no   obligation to monitor posts to this site or to exercise any editorial control   over such posts; however, we reserve the right to review such posts and to   remove any material that, in our judgment, is not appropriate. Posting,   transmitting, promoting, using, distributing or storing content that could   subject us to any legal liability, whether in tort or otherwise, or that is in   violation of any applicable law or regulation, or otherwise contrary to commonly   accepted community standards, is prohibited, including without limitation   information and material protected by copyright, trademark, trade secret,   nondisclosure or confidentiality agreements, or other intellectual property   rights, and material that is obscene, defamatory, constitutes a threat, or   violates export control laws. </p>
<p>        8.2 Defamation; Communications Decency Act Notice. This site is a   provider of &quot;interactive computer services&quot; under the Communications Decency   Act, 47 U.S.C. Section 230, and as such, our liability for defamation and other   claims arising out of any postings to this site by third parties is limited as   described therein. We are not responsible for content or any other information   posted to this site by third parties. We neither warrant the accuracy of such   postings or exercise any editorial control over such posts, nor do we assume any   legal obligation for editorial control of content posted by third parties or   liability in connection with such postings, including any responsibility or   liability for investigating or verifying the accuracy of any content or any   other information contained in such postings.</p>
<p>        8.3 Copyright Infringement; The Digital Millennium Copyright Act   Notice. This site is an Internet &quot;service provider&quot; under the Digital Millennium   Copyright Act, 17 U.S.C. Section 512 (&quot;DMCA&quot;). As Required by the DMCA, this   site maintains specific contact information provided below, including an e-mail   address, for notifications of claimed infringement regarding materials posted to   this site. All notices should be addressed to the contact person specified below   (our agent for notice of claimed infringement):</p>
<p>        Notification of Claimed Infringement:<br />
     Centerfold Strips<br />
     <a href="mailto:info@centerfoldstrips.com">info@centerfoldstrips.com</a><br />
Telephone: 877-427-8747</p>
<p>        You may contact our agent for notice of claimed infringement   specified above with complaints regarding allegedly infringing posted material   and we will investigate those complaints. If the posted material is believed in   good faith by us to violate any applicable law, we will remove or disable access   to any such material, and we will notify the posting party that the material has   been blocked or removed. In notifying us of alleged copyright infringement, the   DMCA requires that you include the following information: (i) description of the   copyrighted work that is the subject of claimed infringement; (ii) description   of the infringing material and information sufficient to permit us to locate the   alleged material; (iii) contact information for you, including your address,   telephone number and/or e-mail address; (iv) a statement by you that you have a   good faith belief that the material in the manner complained of is not   authorized by the copyright owner, or its agent, or by the operation of any law;   (v) a statement by you, signed under penalty of perjury, that the information in   the notification is accurate and that you have the authority to enforce the   copyrights that are claimed to be infringed; and (vi) a physical or electronic   signature of the copyright owner or a person authorized to act on the copyright   owner's behalf. Failure to include all of the above-listed information may   result in the delay of the processing of your complaint.</p>
<p>9. Copyrights. The copyright in all material provided on this site is owned   by CFS or by CFS's licensor(s). You acknowledge and agree that this site   contains proprietary information that is protected by applicable intellectual   property and other laws. You further acknowledge and agree that information   presented to You through this site, including text, graphics, logos, icons,   images and software, and the arrangement and compilation of such content, are   the property of CFS or its content suppliers and is protected by copyrights,   trademarks, service marks, patents or other proprietary rights and laws. CFS   does not grant any license or authorization to any user of its copyrightable   material or other intellectual property, by placing them on this site.   Furthermore, except as stated herein, none of the material may be copied,   reproduced, distributed, republished, downloaded, displayed, posted or   transmitted in any form or by any means, including, but not limited to,   electronic, mechanical, photocopying, recording, or otherwise, without the prior   written permission of CFS or the copyright owner. However, You may print a copy   of the information on this site for Your personal, non-commercial internal use   or records. In so doing, You may not modify the materials and You agree to   retain all copyright and other proprietary notices contained in the materials.   This permission does not give You any ownership rights in the information and   terminates automatically if You breach any of these terms or conditions. If You   make any other use of this site, except as otherwise provided herein, You may   violate copyright and other laws of the United States, other countries, as well   as applicable state laws and may be subject to penalties.</p>
<p>10. Trademarks. The trademarks, service marks, and logos (the &quot;Trademarks&quot;)   used and displayed on this site are registered and unregistered Trademarks of   CFS and others. Nothing on this site should be construed as granting, by   implication, estoppel, or otherwise, any license or right to use any Trademark   displayed on the site, without the written permission of the Trademark owner.   CFS aggressively enforces its intellectual property rights to the fullest extent   of the law. The Trademark(s) CONTRACTMAKER may not be used in any way, including   in advertising or publicity pertaining to distribution of materials on this   site, without prior, written permission. CFS prohibits use of any of the   forgoing names or marks as a metatag or as a &quot;hot&quot; link to any CFS site unless   establishment of such a link is approved in advance by CFS in writing. If You   have any questions regarding any trademarks on the site, please contact CFS.</p>
<p>11. Links.</p>
<p>        11.1 Links to This Site. We grant to you a limited, revocable, and   nonexclusive right to create a hyperlink to the home page of this site so long   as the link does not portray us or our products or services in a false,   misleading, derogatory, or offensive matter. You may not use the our logo, our   trademark, or our name or trademarks, or other proprietary graphic image in the   link without our prior written permission.</p>
<p>        11.2 Links to Third Party Websites. We do not review or control third   party websites that link to or from this site, is not responsible for their   content, and does not represent that their content is accurate or appropriate.   Your use of such third party site is on your own initiative and at your own risk   and may be subject to the other sites' terms of use.</p>
<p>12. Participation In Promotions Of Advertisers. You may enter into   correspondence with or participate in promotions of advertisers promoting their   products or services on this site (&quot;Advertisers&quot;). You acknowledge and agree   that any such correspondence or participation, including the delivery of and the   payment for goods and services, and any other terms, conditions, warranties or   representations associated with such correspondence or promotions, are solely   between You and Advertiser. Digicontracts.com shall have no liability,   obligation or responsibility whatsoever arising out of or in connection with any   such correspondence or participation or transactions.</p>
<p>13. Monitoring. You acknowledge that CFS or its designees reserves the right   to, and may from time to time, monitor any and all activity or information   transmitted or received through this site. CFS, in its sole discretion and   without further notice to You, may (but is not obligated to) review, censor or   prohibit any activity or the transmission or receipt of any Information which   CFS deems inappropriate (such as that specified in above) or that violates any   term or condition of this agreement. During monitoring, information may be   examined, recorded, copied, and used for authorized purposes. Use of this site,   authorized or unauthorized, constitutes consent to such monitoring. Unauthorized   uses and unauthorized users of this site will be prosecuted to the full extent   of the law.</p>
<p>14. NO WARRANTIES. THIS SITE AND ALL INFORMATION CONTAINED ON THIS SITE, AND   EXCEPT TO THE EXTENT EXPRESSLY PROVIDED IN A LICENSE AGREEMENT FOR SOFTWARE OR   CONTENT, ALL GOODS AND SERVICES OBTAINED THROUGH THIS SITE, ARE PROVIDED ON AN   &quot;AS IS&quot; BASIS FROM CFS AND ITS INFORMATION PROVIDERS, CFS AND ITS AFFILIATES AND   CONTENT PROVIDERS MAKE NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR   IMPLIED, RELATING TO THIS AGREEMENT, THE PERFORMANCE UNDER THIS AGREEMENT, THE   SERVICES AVAILABLE ON THIS SITE, THE OPERATION OF THE SOFTWARE AVAILABLE ON THIS   SITE, THE TRANSACTIONS PERFORMED ON THIS SITE, OR THE INFORMATION, CONTENT,   MATERIALS AND/OR PRODUCTS INCLUDED ON THIS S ITE. TO THE FULLEST EXTENT   PERMISSIBLE BY APPLICABLE LAW, EACH OF CFS AND CFS'S AFFILIATES AND CONTENT   PROVIDERS DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING BUT NOT   LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR P   URPOSE, TITLE AND/OR NONINFRINGMENT. YOU ACKNOWLEDGE THAT NEITHER THIS SITE NOR   THE CONTRACTMAKER INTERNET SERVICE IS ENGAGED IN PROVIDING PROFESSIONAL LEGAL   SERVICES OR LEGAL ADVICE, AND THAT IT IS YOUR RESPONSIBILITY TO SEEK COMPETENT   LEGAL COUNSEL TO ADVISE YOU REGARDING THE APPLICABILITY OF ANY CONTENT AVAILABLE   ON THIS SITE TO SPECIFIC FACTUAL SITUATIONS. NO ATTORNEY-CLIENT RELATIONSHIP IS   INTENDED NOR CREATED THROUGH YOUR USE OF THIS SITE, THE CONTRACTMAKER INTERNET   SERVICE, OR THE CONTENT. YOU ASSUME THE ENTIRE RISK OF SELECTION AND USE OF THE   CONTENT AVAILABLE AT THIS SITE. WITHOUT LIMITING THE FOREGOING, NONE OF CFS NOR   CFS'S AFFILIATES OR CONTENT PROVIDERS MAKES ANY WARRANTY THAT (i) THE GOODS OR   SERVICES OFFERED ON THIS SITE WILL MEET YOUR REQUIREMENTS, (ii) THE GOODS OR   SERVICES OFFERED ON THIS SITE WILL BE UNINTERRUPTED, TIMELY, SECURE, OR   ERROR-FREE, (iii) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE GOODS OR   SERVICES WILL BE ACCURATE OR RELIABLE, (iv) THE CONTENT OR INFORMATION AVAILABLE   ON THIS SITE IS COMPLETE, ACCURATE OR AVAILABLE, OR (v) THE QUALITY OF ANY   PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU   THROUGH THE SERVICES WILL MEET YOUR EXPECTATIONS. NO ADVICE OR INFORMATION,   WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM CFS OR THROUGH THIS SITE SHALL   CREATE ANY WARRANTY NOT EXPRESSLY MADE HEREIN.</p>
<p>15. LIMITED LIABILITY. CFS AND ALL OF CFS's AFFILIATES AND CONTENT PROVIDERS   AND THEIR RESPECTIVE SHAREHOLDERS AND AFFILIATES SHALL NOT BE LIABLE FOR ANY   LOSS OF BUSINESS, LOSS OF USE OR OF DATA, INTERRUPTION OF BUSINESS, LOST PROFITS   OR GOODWILL, OR OTHER INDIRECT, SPECIAL, INCIDENTAL, EXEMPLARY OR CONSEQUENTIAL   DAMAGES OF ANY KIND ARISING OUT OF THIS AGREEMENT, EVEN IF THEY HAVE BEEN   ADVISED OF THE POSSIBILITY OF SUCH LOSS AND WHETHER OR NOT THEY HAD ANY   KNOWLEDGE, ACTUAL OR CONSTRUCTIVE, THAT SUCH DAMAGES MIGHT BE INCURRED, AND   NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. THIS   EXCLUSION INCLUDES ANY LIABILITY THAT MAY ARISE OUT OF THIRD-PARTY CLAIMS   AGAINST YOU. YOU AGREE THAT REGARDLESS OF ANY STATUTE OR LAW TO THE CONTRARY,   ANY CLAIM OR CAUSE OF ACTION ARISING OUT OF OR RELATED TO USE OF THE GOODS OR   SERVICES PROVIDED ON THIS SITE OR THIS AGREEMENT MUST BE FILED WITHIN ONE (1)   YEAR AFTER SUCH CLAIM OR CAUSE OF ACTION AROSE OR BE FOREVER BARRED. YOU FURTHER   AGREE IF YOU BECOME ENTITLED TO ANY RECOVERY, THAT YOUR RECOVERY SHALL BE   LIMITED TO THE AMOUNT OF FEES OR PAYMENTS MADE TO CFS, IF ANY, FOR THE SERVICE,   SOFTWARE OR CONTENT AT ISSUE.</p>
<p>16. Indemnity. You shall defend, indemnify, and hold harmless CFS and its   content providers and their respective shareholders, affiliates, employees,   agents, successors, officers, and assigns, from any suits, losses, claims,   demands, liabilities, costs and expenses (including attorney and accounting   fees) that they may sustain or incur arising from your failure to have any   documents drafted through this site reviewed by Your attorney acting within an   attorney-client relationship.</p>
<p>17. Beneficiaries of this Agreement; No Other Agreements. The rights and   limitations in this agreement are for the benefit of CFS and each of CFS's   content providers, each of which shall have the right to enforce its rights   hereunder directly and on its own behalf.</p>
<p>18. Termination. You agree that CFS may, at its sole discretion, deny You   access to the site and disable any user name and password associated with You   for any reason, including, without limitation, if CFS believes that You have   violated or acted inconsistently with the letter or spirit of this agreement.   CFS reserves the right at any time and from time to time to modify or   discontinue, temporarily or permanently, the services offered under this site   (or any part thereof) with or without notice. You agree that CFS shall not be   liable to You or to any third party for any modification, suspension or   discontinuance of the services offered under this site.</p>
<p>19. Consumer Rights. CFS maintains specific contact information including an   e-mail address for notifications of complaints and for inquiries regarding   pricing policies in accordance with California Civil Code Section 1789.3. You   may contact CFS with complaints and inquiries regarding pricing and CFS will   investigate those matters and respond to the inquiries.All correspondence should   be addressed to CFS's agent for notice at the following address:</p>
<p>Notification of Consumer Rights Complaint or Pricing Inquiry:<br />
     Centerfold Strips<br />
     <a href="mailto:info@centerfoldstrips.com">info@centerfoldstrips.com</a><br />
     Telephone: 877-427-8747</p>
<p>20. Controlling Law. This Agreement shall be construed under the laws of the   State of New York, USA, excluding rules regarding conflicts of law. The   application the United Nations Convention of Contracts for the International   Sale of Goods is expressly excluded.</p>
<p>21. Jurisdiction And Venue. You and CFS agree to submit to the exclusive   personal jurisdiction of the courts of Manhattan County in the State of New York,   USA in all legal proceedings that are that are not arbitrated under this   Agreement .</p>
<p>22. Arbitration. Except for actions to protect intellectual property rights   and to enforce an arbitrator's decision hereunder, all disputes, controversies,   or claims arising out of or relating to this Agreement or a breach thereof shall   be submitted to and finally resolved by arbitration under the rules of the   American Arbitration Association (&quot;AAA&quot;) then in effect. There shall be one   arbitrator, and such arbitrator shall be chosen by mutual agreement of the   parties in accordance with AAA rules. The arbitration shall take place in   Atlanta, Georgia, and may be conducted by telephone or online. The arbitrator   shall apply the laws of the State of Georgia, USA to all issues in dispute. The   controversy or claim shall be arbitrated on an individual basis, and shall not   be consolidated in any arbitration with any claim or controversy of any other   party. The findings of the arbitrator shall be final and binding on the parties,   and may be entered in any court of competent jurisdiction for enforcement.   Enforcements of any award or judgment shall be governed by the United Nations   Convention on the Recognition and Enforcement of Foreign Arbitral Awards. Should   either party file an action contrary to this provision, the other party may   recover attorney's fees and costs up to $1000.00.</p>
</asp:Content>

